name: UltimateBottles
main: com.songoda.ultimatebottles.UltimateBottles
version: maven-version-number
author: Songoda
api-version: 1.13
commands:
  ultimatebottles:
    description: View information on this plugin.
    default: true
    aliases: [ub, bottles, bottle]
    usage: /<command> [reload]

